package runner

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"time"

	"github.com/babelsuite/babelsuite/internal/apisix"
	"github.com/babelsuite/babelsuite/internal/logstream"
	"github.com/babelsuite/babelsuite/internal/suites"
)

// apisixTrafficConfig is the JSON payload sent to the traffic-cannon Lua plugin.
type apisixTrafficConfig struct {
	Target   string              `json:"target"`
	Model    string              `json:"model"`
	RPS      float64             `json:"rps,omitempty"`
	Stages   []apisixStageConfig `json:"stages"`
	UsersDef []apisixUserConfig  `json:"users_def"`
}

type apisixStageConfig struct {
	Users    int     `json:"users"`
	Duration float64 `json:"duration"` // seconds
	Stop     bool    `json:"stop,omitempty"`
}

type apisixUserConfig struct {
	Name   string             `json:"name"`
	Weight int                `json:"weight"`
	Tasks  []apisixTaskConfig `json:"tasks"`
}

type apisixTaskConfig struct {
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Body    string            `json:"body,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}

// apisixTrafficResult is the JSON histogram returned by the Lua plugin.
type apisixTrafficResult struct {
	Total    int     `json:"total"`
	Failures int     `json:"failures"`
	P50      float64 `json:"p50"`
	P95      float64 `json:"p95"`
	P99      float64 `json:"p99"`
	Min      float64 `json:"min"`
	Max      float64 `json:"max"`
}

// canUseAPISIXTraffic returns true when the step environment carries an APISIX
// gateway URL (APISIX_TRAFFIC_URL).  The plugin and trigger route are already
// baked into the sidecar's apisix.yaml by RenderStandaloneConfig — no Admin
// API calls are needed at runtime.
func canUseAPISIXTraffic(step StepSpec) bool {
	return strings.TrimSpace(step.Env["APISIX_TRAFFIC_URL"]) != ""
}

// runAPISIXTraffic delegates load generation to an APISIX/OpenResty sidecar.
// The babelsuite-traffic-cannon plugin is already registered in the sidecar's
// apisix.yaml (generated by RenderStandaloneConfig), so this function simply:
//  1. Translates the LoadSpec into the JSON config the Lua plugin expects.
//  2. POSTs it to /_babelsuite/traffic/start and waits for the synchronous result.
//  3. Merges the histogram into loadStats for finalizeLoadStep.
func runAPISIXTraffic(ctx context.Context, step StepSpec, emit func(logstream.Line), stats *loadStats) error {
	gatewayURL := strings.TrimSuffix(strings.TrimSpace(step.Env["APISIX_TRAFFIC_URL"]), "/")

	emit(line(step, "info", fmt.Sprintf("[%s] Delegating traffic generation to APISIX sidecar at %s.", step.Node.Name, gatewayURL)))

	cfg := buildAPISIXConfig(step.Load)
	cfgJSON, err := json.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("apisix traffic: marshal config: %w", err)
	}

	emit(line(step, "info", fmt.Sprintf("[%s] Triggering traffic cannon: model=%s stages=%d target=%s.", step.Node.Name, cfg.Model, len(cfg.Stages), cfg.Target)))

	result, err := triggerAPISIXTraffic(ctx, gatewayURL, cfgJSON, cfg)
	if err != nil {
		return fmt.Errorf("apisix traffic: trigger failed: %w", err)
	}

	applyAPISIXResult(result, stats)
	emit(line(step, "info", fmt.Sprintf("[%s] APISIX run completed: total=%d failures=%d p50=%.1fms p95=%.1fms p99=%.1fms.", step.Node.Name, result.Total, result.Failures, result.P50, result.P95, result.P99)))
	return nil
}

// buildAPISIXConfig converts a suites.LoadSpec into the JSON structure expected
// by the babelsuite-traffic-cannon Lua plugin.
func buildAPISIXConfig(spec *suites.LoadSpec) apisixTrafficConfig {
	model := "closed"
	switch spec.Variant {
	case "traffic.constant_throughput", "traffic.open_model":
		model = "open"
	}

	stages := make([]apisixStageConfig, 0, len(spec.Stages))
	for _, s := range spec.Stages {
		stages = append(stages, apisixStageConfig{
			Users:    s.Users,
			Duration: s.Duration.Seconds(),
			Stop:     s.Stop,
		})
	}
	if len(stages) == 0 {
		stages = []apisixStageConfig{{Users: 1, Duration: 60}}
	}

	users := make([]apisixUserConfig, 0, len(spec.Users))
	for _, u := range spec.Users {
		tasks := make([]apisixTaskConfig, 0, len(u.Tasks))
		for _, t := range u.Tasks {
			tasks = append(tasks, apisixTaskConfig{
				Method:  firstNonEmptyStr(t.Request.Method, "GET"),
				Path:    firstNonEmptyStr(t.Request.Path, "/"),
				Body:    t.Request.Body,
				Headers: t.Request.Headers,
			})
		}
		users = append(users, apisixUserConfig{
			Name:   u.Name,
			Weight: u.Weight,
			Tasks:  tasks,
		})
	}
	if len(users) == 0 {
		users = []apisixUserConfig{{Name: "default", Weight: 1, Tasks: []apisixTaskConfig{{Method: "GET", Path: "/"}}}}
	}

	return apisixTrafficConfig{
		Target:   spec.Target,
		Model:    model,
		RPS:      spec.RequestsPerS,
		Stages:   stages,
		UsersDef: users,
	}
}

// triggerAPISIXTraffic fires POST /_babelsuite/traffic/start and waits for the
// synchronous JSON histogram response.  The Lua plugin blocks until the full
// test completes, so the HTTP timeout is derived from the total stage duration.
func triggerAPISIXTraffic(ctx context.Context, gatewayURL string, cfgJSON []byte, cfg apisixTrafficConfig) (*apisixTrafficResult, error) {
	var totalDuration time.Duration
	for _, s := range cfg.Stages {
		totalDuration += time.Duration(s.Duration * float64(time.Second))
	}
	timeout := totalDuration + 5*time.Minute
	if timeout < 10*time.Minute {
		timeout = 10 * time.Minute
	}

	reqCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	req, err := http.NewRequestWithContext(reqCtx, http.MethodPost,
		gatewayURL+apisix.TrafficCannonTriggerRoute,
		bytes.NewReader(cfgJSON))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := (&http.Client{}).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("APISIX sidecar returned HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}

	var result apisixTrafficResult
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("parse response JSON: %w", err)
	}
	return &result, nil
}

// applyAPISIXResult merges the Lua histogram result into the native loadStats
// so that finalizeLoadStep / evaluateLoadThresholds work unchanged.
func applyAPISIXResult(result *apisixTrafficResult, stats *loadStats) {
	stats.mu.Lock()
	defer stats.mu.Unlock()

	stats.Requests = result.Total
	stats.Failures = result.Failures
	stats.FinishedAt = time.Now()

	synthetic := syntheticLatencies(result.Min, result.P50, result.P95, result.P99, result.Max, result.Total)
	stats.Latencies = synthetic

	if len(stats.Stages) == 0 {
		stats.Stages[0] = &loadStageStats{
			Index:      0,
			Requests:   result.Total,
			Failures:   result.Failures,
			Latencies:  synthetic,
			StartedAt:  stats.StartedAt,
			FinishedAt: stats.FinishedAt,
		}
	}
	if result.Total > stats.PeakUsers {
		stats.PeakUsers = result.Total
	}
}

// syntheticLatencies reconstructs a latency slice from percentile breakpoints
// so the existing percentile helpers in loadStats.summary() produce correct
// numbers.  n is capped at 100 for memory safety.
func syntheticLatencies(minMs, p50, p95, p99, maxMs float64, n int) []time.Duration {
	if n <= 0 {
		n = 4
	}
	if n > 100 {
		n = 100
	}
	points := []float64{minMs, p50, p95, p99, maxMs}
	sort.Float64s(points)

	out := make([]time.Duration, 0, n)
	for i := 0; i < n; i++ {
		idx := int(float64(i) / float64(n) * float64(len(points)))
		if idx >= len(points) {
			idx = len(points) - 1
		}
		out = append(out, time.Duration(points[idx]*float64(time.Millisecond)))
	}
	return out
}

func firstNonEmptyStr(a, b string) string {
	if strings.TrimSpace(a) != "" {
		return a
	}
	return b
}
