name: Local Debug
description: Relaxed certificates and hot-reloadable providers.
default: true
runtime:
  suite: identity-broker
  repository: localhost:5000/security/identity-broker
  profileFile: local.yaml
modules:
    - vault
    - postgres
observability:
  logs: structured
  traces: enabled
  metrics: enabled
