apiVersion: mocks.babelsuite.io/v1alpha1
kind: MockOperation
metadata:
    metadataPath: mock/oidc/jwks.metadata.yaml
    operationId: begin-login
    sourceArtifact: mock/oidc/jwks.json
    suite: identity-broker
spec:
    adapter: rest
    delayMillis: 0
    fallback: null
    parameterConstraints: []
    resolverUrl: /internal/mock-data/identity-broker/broker-api/begin-login
    runtimeUrl: /mocks/rest/identity-broker/broker-api/sessions/login?provider=oidc
    state: null
