// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file logstream/v1/logstream.proto (package babelsuite.logstream.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file logstream/v1/logstream.proto.
 */
export const file_logstream_v1_logstream: GenFile = /*@__PURE__*/
  fileDesc("Chxsb2dzdHJlYW0vdjEvbG9nc3RyZWFtLnByb3RvEhdiYWJlbHN1aXRlLmxvZ3N0cmVhbS52MSJUCgRMaW5lEg4KBnNvdXJjZRgBIAEoCRIRCgl0aW1lc3RhbXAYAiABKAkSDQoFbGV2ZWwYAyABKAkSDAoEa2luZBgEIAEoCRIMCgR0ZXh0GAUgASgJIlcKBlJlY29yZBIKCgJpZBgBIAEoBRIUCgxleGVjdXRpb25faWQYAiABKAkSKwoEbGluZRgDIAEoCzIdLmJhYmVsc3VpdGUubG9nc3RyZWFtLnYxLkxpbmVCSFpGZ2l0aHViLmNvbS9iYWJlbHN1aXRlL2JhYmVsc3VpdGUvZ2VuL3Byb3RvL2dvL2xvZ3N0cmVhbS92MTtsb2dzdHJlYW12MWIGcHJvdG8z");

/**
 * @generated from message babelsuite.logstream.v1.Line
 */
export type Line = Message<"babelsuite.logstream.v1.Line"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;

  /**
   * @generated from field: string timestamp = 2;
   */
  timestamp: string;

  /**
   * @generated from field: string level = 3;
   */
  level: string;

  /**
   * @generated from field: string kind = 4;
   */
  kind: string;

  /**
   * @generated from field: string text = 5;
   */
  text: string;
};

/**
 * Describes the message babelsuite.logstream.v1.Line.
 * Use `create(LineSchema)` to create a new message.
 */
export const LineSchema: GenMessage<Line> = /*@__PURE__*/
  messageDesc(file_logstream_v1_logstream, 0);

/**
 * @generated from message babelsuite.logstream.v1.Record
 */
export type Record = Message<"babelsuite.logstream.v1.Record"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string execution_id = 2;
   */
  executionId: string;

  /**
   * @generated from field: babelsuite.logstream.v1.Line line = 3;
   */
  line?: Line | undefined;
};

/**
 * Describes the message babelsuite.logstream.v1.Record.
 * Use `create(RecordSchema)` to create a new message.
 */
export const RecordSchema: GenMessage<Record> = /*@__PURE__*/
  messageDesc(file_logstream_v1_logstream, 1);

