// Code generated by BabelSuite. DO NOT EDIT.
suite: "payment-suite"
artifact: "mock/wiremock/stripe/refund.cue"
message: "No seeded exchanges matched this mock file, so BabelSuite generated a placeholder preview."
