package suites

var returnsControlPlaneSeedSources = []SourceFile{
	{
		Path:     "mock/returns/create-return.cue",
		Language: "cue",
		Content: `// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "returns-control-plane"
artifact: "mock/returns/create-return.cue"
operationId: "create-return"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/openapi/returns.yaml#/paths/~1returns/post"
resolverUrl: "/internal/mock-data/returns-control-plane/returns-api/create-return"
runtimeUrl: "/mocks/rest/returns-control-plane/returns-api/returns?scenario=approved"
examples: {
  "approved-standard": {
    dispatch: [{"from":"query","param":"scenario","value":"approved"}]
    requestSchema: {
      headers: {
        "content-type": "application/json"
        "x-suite-profile": "canary.yaml"
      }
      body: {
        amountCents: 4200
        orderId: "ord_1001"
        returnReason: "damaged"
      }
    }
    responseSchema: {
      status: "201"
      mediaType: "application/json"
      headers: {
        "x-mock-source": "returns-approved"
      }
      body: {
        status: "approved"
        queue: "auto"
        refundMode: "instant_credit"
        returnId: string @gen(kind="int", prefix="ret_", min=1001, max=9999)
        servedAt: string @gen(kind="timestamp")
        traceId: string @gen(kind="uuid")
      }
    }
  }
  "manual-review": {
    dispatch: [{"from":"query","param":"scenario","value":"manual-review"}]
    requestSchema: {
      headers: {
        "content-type": "application/json"
        "x-suite-profile": "peak.yaml"
      }
      body: {
        amountCents: 15900
        orderId: "ord_2042"
        returnReason: "suspicious_activity"
      }
    }
    responseSchema: {
      status: "202"
      mediaType: "application/json"
      headers: {
        "x-review-queue": "manual"
      }
      body: {
        status: "manual_review"
        queue: "manual"
        refundMode: "agent_review"
        returnId: string @gen(kind="int", prefix="ret_", min=2000, max=9999)
        servedAt: string @gen(kind="timestamp")
        traceId: string @gen(kind="uuid")
      }
    }
  }
}
`,
	},
	{
		Path:     "mock/returns/get-return.cue",
		Language: "cue",
		Content: `// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "returns-control-plane"
artifact: "mock/returns/get-return.cue"
operationId: "get-return"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/openapi/returns.yaml#/paths/~1returns~1{returnId}/get"
resolverUrl: "/internal/mock-data/returns-control-plane/returns-api/get-return"
runtimeUrl: "/mocks/rest/returns-control-plane/returns-api/returns/ret_1001"
examples: {
  "return-state": {
    dispatch: []
    requestSchema: {
      headers: {
        "x-request-id": "req-100"
      }
      body: null
    }
    responseSchema: {
      status: "200"
      mediaType: "application/json"
      headers: {
        "x-mock-source": "returns-state"
      }
      body: {
        status: string @resolve(path="state.status")
        profile: string @resolve(path="state.profile")
        refundMode: string @resolve(path="state.refundMode")
        returnId: string @resolve(path="request.path.returnId")
        reviewQueue: string @resolve(path="state.reviewQueue")
        servedAt: string @gen(kind="timestamp")
        servedBy: string @resolve(path="request.headers.x-mock-node", fallback="apisix-sidecar")
        traceId: string @gen(kind="uuid")
      }
    }
  }
}
`,
	},
}

var soapClaimsHubSeedSources = []SourceFile{
	{
		Path:     "mock/claims/claim-service.cue",
		Language: "cue",
		Content: `// Code generated by BabelSuite. DO NOT EDIT.
"$schema": "https://schemas.babelsuite.dev/mock-exchange-source-v1.json"
suite: "soap-claims-hub"
artifact: "mock/claims/claim-service.cue"
operationId: "claim-service"
adapter: "rest"
dispatcher: "apisix"
contractPath: "api/wsdl/claims.wsdl#ClaimService"
resolverUrl: "/internal/mock-data/soap-claims-hub/claims-soap/claim-service"
runtimeUrl: "/mocks/rest/soap-claims-hub/claims-soap/ClaimService"
examples: {
  GetClaimStatus: {
    dispatch: [{"from":"header","param":"soapaction","value":"urn:GetClaimStatus"}]
    requestSchema: {
      headers: {
        "content-type": "text/xml; charset=utf-8"
        soapaction: "urn:GetClaimStatus"
      }
      body: "\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003csoapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:clm=\"urn:claims:v1\"\u003e\n  \u003csoapenv:Header/\u003e\n  \u003csoapenv:Body\u003e\n    \u003cclm:GetClaimStatusRequest\u003e\n      \u003cclm:ClaimId\u003eclm_2048\u003c/clm:ClaimId\u003e\n    \u003c/clm:GetClaimStatusRequest\u003e\n  \u003c/soapenv:Body\u003e\n\u003c/soapenv:Envelope\u003e"
    }
    responseSchema: {
      status: "200"
      mediaType: "text/xml; charset=utf-8"
      headers: {
        "x-mock-source": "soap-claim-status"
      }
      body: string @compose("\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003csoapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:clm=\"urn:claims:v1\"\u003e\n  \u003csoapenv:Body\u003e\n    \u003cclm:GetClaimStatusResponse\u003e\n      \u003cclm:ClaimId\u003eclm_2048\u003c/clm:ClaimId\u003e\n      \u003cclm:Status\u003eIN_REVIEW\u003c/clm:Status\u003e\n      \u003cclm:Owner\u003emanual_queue\u003c/clm:Owner\u003e\n      \u003cclm:TraceId\u003e", gen(kind="uuid"), "\u003c/clm:TraceId\u003e\n      \u003cclm:ServedAt\u003e", gen(kind="timestamp"), "\u003c/clm:ServedAt\u003e\n    \u003c/clm:GetClaimStatusResponse\u003e\n  \u003c/soapenv:Body\u003e\n\u003c/soapenv:Envelope\u003e")
    }
  }
  SubmitClaim: {
    dispatch: [{"from":"header","param":"soapaction","value":"urn:SubmitClaim"}]
    requestSchema: {
      headers: {
        "content-type": "text/xml; charset=utf-8"
        soapaction: "urn:SubmitClaim"
        "x-suite-profile": "canary.yaml"
      }
      body: "\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003csoapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:clm=\"urn:claims:v1\"\u003e\n  \u003csoapenv:Header/\u003e\n  \u003csoapenv:Body\u003e\n    \u003cclm:SubmitClaimRequest\u003e\n      \u003cclm:PolicyNumber\u003ePL-1024\u003c/clm:PolicyNumber\u003e\n      \u003cclm:LossType\u003ewater\u003c/clm:LossType\u003e\n      \u003cclm:Amount\u003e4200\u003c/clm:Amount\u003e\n    \u003c/clm:SubmitClaimRequest\u003e\n  \u003c/soapenv:Body\u003e\n\u003c/soapenv:Envelope\u003e"
    }
    responseSchema: {
      status: "200"
      mediaType: "text/xml; charset=utf-8"
      headers: {
        "x-mock-source": "soap-submit-claim"
      }
      body: string @compose("\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003csoapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:clm=\"urn:claims:v1\"\u003e\n  \u003csoapenv:Body\u003e\n    \u003cclm:SubmitClaimResponse\u003e\n      \u003cclm:ClaimId\u003eclm_", gen(kind="int", min=1001, max=9999), "\u003c/clm:ClaimId\u003e\n      \u003cclm:Decision\u003eAPPROVED\u003c/clm:Decision\u003e\n      \u003cclm:Profile\u003e", resolve(path="request.headers.x-suite-profile", fallback="local.yaml"), "\u003c/clm:Profile\u003e\n      \u003cclm:TraceId\u003e", gen(kind="uuid"), "\u003c/clm:TraceId\u003e\n      \u003cclm:ServedAt\u003e", gen(kind="timestamp"), "\u003c/clm:ServedAt\u003e\n    \u003c/clm:SubmitClaimResponse\u003e\n  \u003c/soapenv:Body\u003e\n\u003c/soapenv:Envelope\u003e")
    }
  }
}
`,
	},
}
