package examplegen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

func formatCUE(value any) string {
	builder := &strings.Builder{}
	builder.WriteString("// Code generated by BabelSuite. DO NOT EDIT.\n")

	root, ok := value.(map[string]any)
	if !ok {
		writeCUEValue(builder, value, 0)
		builder.WriteString("\n")
		return builder.String()
	}

	writeCUEFields(builder, root, 0)
	return builder.String()
}

func writeCUEFields(builder *strings.Builder, fields map[string]any, indent int) {
	keys := orderedCUEKeys(fields)
	for index, key := range keys {
		writeCUEIndent(builder, indent)
		builder.WriteString(formatCUELabel(key))
		builder.WriteString(": ")
		writeCUEValue(builder, fields[key], indent)
		if index < len(keys)-1 {
			builder.WriteString("\n")
		}
	}
	builder.WriteString("\n")
}

func writeCUEValue(builder *strings.Builder, value any, indent int) {
	if schema, ok := value.(map[string]any); ok && isCUESchemaNode(schema) {
		writeCUESchema(builder, schema, indent)
		return
	}

	switch typed := value.(type) {
	case map[string]any:
		builder.WriteString("{\n")
		writeCUEFields(builder, typed, indent+1)
		writeCUEIndent(builder, indent)
		builder.WriteString("}")
	case []any:
		writeCUEList(builder, typed, indent)
	case []string:
		items := make([]any, 0, len(typed))
		for _, item := range typed {
			items = append(items, item)
		}
		writeCUEList(builder, items, indent)
	default:
		builder.WriteString(formatCUELiteral(value))
	}
}

func writeCUEList(builder *strings.Builder, items []any, indent int) {
	if len(items) == 0 {
		builder.WriteString("[]")
		return
	}

	builder.WriteString("[\n")
	for index, item := range items {
		writeCUEIndent(builder, indent+1)
		writeCUEValue(builder, item, indent+1)
		if index < len(items)-1 {
			builder.WriteString(",")
		}
		builder.WriteString("\n")
	}
	writeCUEIndent(builder, indent)
	builder.WriteString("]")
}

func writeCUESchema(builder *strings.Builder, schema map[string]any, indent int) {
	if compose, ok := schema["x-babel-compose"]; ok {
		builder.WriteString(cueSchemaTypeExpr(schema))
		builder.WriteString(" ")
		builder.WriteString(formatCUEAttribute("compose", composeAttributeArgs(compose)))
		return
	}
	if generate, ok := schema["x-babel-generate"]; ok {
		builder.WriteString(cueSchemaTypeExpr(schema))
		builder.WriteString(" ")
		builder.WriteString(formatCUEAttribute("gen", directiveAttributeArgs(generate)))
		return
	}
	if resolve, ok := schema["x-babel-resolve"]; ok {
		builder.WriteString(cueSchemaTypeExpr(schema))
		builder.WriteString(" ")
		builder.WriteString(formatCUEAttribute("resolve", directiveAttributeArgs(resolve)))
		return
	}
	if template, ok := schema["x-babel-template"]; ok {
		builder.WriteString(cueSchemaTypeExpr(schema))
		builder.WriteString(" ")
		builder.WriteString(formatCUEAttribute("template", []string{formatCUELiteral(template)}))
		return
	}
	if example, exists := schema["example"]; exists {
		builder.WriteString(formatCUELiteral(example))
		return
	}

	schemaType := strings.TrimSpace(fmt.Sprint(schema["type"]))
	switch schemaType {
	case "object":
		properties, _ := schema["properties"].(map[string]any)
		builder.WriteString("{\n")
		keys := orderedCUEKeys(properties)
		for index, key := range keys {
			writeCUEIndent(builder, indent+1)
			builder.WriteString(formatCUELabel(key))
			builder.WriteString(": ")
			writeCUEValue(builder, properties[key], indent+1)
			if index < len(keys)-1 {
				builder.WriteString("\n")
			}
		}
		builder.WriteString("\n")
		writeCUEIndent(builder, indent)
		builder.WriteString("}")
	case "array":
		if items, exists := schema["items"]; exists {
			builder.WriteString("[\n")
			writeCUEIndent(builder, indent+1)
			writeCUEValue(builder, items, indent+1)
			builder.WriteString("\n")
			writeCUEIndent(builder, indent)
			builder.WriteString("]")
			return
		}
		builder.WriteString("[]")
	case "null":
		builder.WriteString("null")
	default:
		builder.WriteString(cueSchemaTypeExpr(schema))
	}
}

func isCUESchemaNode(value map[string]any) bool {
	if len(value) == 0 {
		return false
	}
	_, hasType := value["type"]
	_, hasExample := value["example"]
	_, hasGenerate := value["x-babel-generate"]
	_, hasResolve := value["x-babel-resolve"]
	_, hasCompose := value["x-babel-compose"]
	_, hasTemplate := value["x-babel-template"]
	return hasType || hasExample || hasGenerate || hasResolve || hasCompose || hasTemplate
}

func cueSchemaTypeExpr(schema map[string]any) string {
	switch strings.TrimSpace(fmt.Sprint(schema["type"])) {
	case "integer":
		return "int"
	case "number":
		return "number"
	case "boolean":
		return "bool"
	case "null":
		return "null"
	case "string":
		return "string"
	default:
		return "string"
	}
}

func directiveAttributeArgs(value any) []string {
	node, ok := value.(map[string]any)
	if !ok {
		return nil
	}

	keys := orderedDirectiveKeys(node)
	args := make([]string, 0, len(keys))
	for _, key := range keys {
		if key == "" {
			continue
		}
		args = append(args, key+"="+formatCUELiteral(node[key]))
	}
	return args
}

func composeAttributeArgs(value any) []string {
	parts, ok := value.([]any)
	if !ok {
		return nil
	}

	args := make([]string, 0, len(parts))
	for _, part := range parts {
		switch typed := part.(type) {
		case string:
			args = append(args, formatCUELiteral(typed))
		case map[string]any:
			if generate, exists := typed["generate"]; exists {
				args = append(args, inlineDirectiveCall("gen", directiveAttributeArgs(generate)))
				continue
			}
			if resolve, exists := typed["resolve"]; exists {
				args = append(args, inlineDirectiveCall("resolve", directiveAttributeArgs(resolve)))
				continue
			}
		default:
			args = append(args, formatCUELiteral(part))
		}
	}
	return args
}

func inlineDirectiveCall(name string, args []string) string {
	return name + "(" + strings.Join(args, ", ") + ")"
}

func formatCUEAttribute(name string, args []string) string {
	return "@" + name + "(" + strings.Join(args, ", ") + ")"
}

func formatCUELabel(label string) string {
	if isCUEIdentifier(label) {
		return label
	}
	return formatCUELiteral(label)
}

func isCUEIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, char := range value {
		switch {
		case index == 0 && (char == '_' || (char >= 'A' && char <= 'Z') || (char >= 'a' && char <= 'z')):
		case index > 0 && (char == '_' || (char >= 'A' && char <= 'Z') || (char >= 'a' && char <= 'z') || (char >= '0' && char <= '9')):
		default:
			return false
		}
	}
	return true
}

func orderedCUEKeys(fields map[string]any) []string {
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		return cueKeyRank(keys[i]) < cueKeyRank(keys[j]) || (cueKeyRank(keys[i]) == cueKeyRank(keys[j]) && keys[i] < keys[j])
	})
	return keys
}

func orderedDirectiveKeys(fields map[string]any) []string {
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		return directiveKeyRank(keys[i]) < directiveKeyRank(keys[j]) || (directiveKeyRank(keys[i]) == directiveKeyRank(keys[j]) && keys[i] < keys[j])
	})
	return keys
}

func cueKeyRank(key string) int {
	switch key {
	case "$schema":
		return 0
	case "suite":
		return 1
	case "artifact":
		return 2
	case "operationId":
		return 3
	case "adapter":
		return 4
	case "dispatcher":
		return 5
	case "contractPath":
		return 6
	case "resolverUrl":
		return 7
	case "runtimeUrl":
		return 8
	case "examples":
		return 9
	case "dispatch":
		return 10
	case "requestSchema":
		return 11
	case "responseSchema":
		return 12
	case "status":
		return 13
	case "mediaType":
		return 14
	case "headers":
		return 15
	case "body":
		return 16
	default:
		return 100
	}
}

func directiveKeyRank(key string) int {
	switch key {
	case "kind":
		return 0
	case "path":
		return 1
	case "prefix":
		return 2
	case "suffix":
		return 3
	case "min":
		return 4
	case "max":
		return 5
	case "length":
		return 6
	case "layout":
		return 7
	case "fallback":
		return 8
	case "options":
		return 9
	default:
		return 100
	}
}

func writeCUEIndent(builder *strings.Builder, indent int) {
	builder.WriteString(strings.Repeat("  ", indent))
}

func formatCUELiteral(value any) string {
	switch typed := value.(type) {
	case string:
		body, _ := json.Marshal(typed)
		return string(body)
	case bool:
		if typed {
			return "true"
		}
		return "false"
	case nil:
		return "null"
	case int, int8, int16, int32, int64, float32, float64, uint, uint8, uint16, uint32, uint64:
		return fmt.Sprint(typed)
	case []any:
		items := make([]string, 0, len(typed))
		for _, item := range typed {
			items = append(items, formatCUELiteral(item))
		}
		return "[" + strings.Join(items, ", ") + "]"
	case []string:
		items := make([]string, 0, len(typed))
		for _, item := range typed {
			items = append(items, formatCUELiteral(item))
		}
		return "[" + strings.Join(items, ", ") + "]"
	default:
		body, err := json.Marshal(typed)
		if err != nil {
			return `""`
		}
		return string(body)
	}
}
